### PR TITLE
reorg import statement

### PR DESCRIPTION
**Pull request by cmingxu**
Signed-off-by: kevin.xu <cming.xu@gmail.com>

### CODE REVIEW

**Comment by cfc4n** [comment]
thanks for contributiong. but I don't understand your code style.  eCapture format by `gofmt` now.
Could you give the code style name you used.

**Comment by cmingxu** [comment]
gofmt does not support import reorder, those changes are made manully.

**Comment by cfc4n** [comment]
> gofmt does not support import reorder, those changes are made manully.

uh... what is the code style you used? which standard?

**Comment by cfc4n** [comment]
hi @cmingxu , could you give me more detail for this pr?

**Comment by cfc4n** [comment]
no response, closed.

**Pull request closed without merging**
