### PR TITLE
ebpf: remove detection of BPF config when running at container #127

### PR DESCRIPTION
**Pull request by cfc4n**
remove detection of BPF config when running at container.

In Github Action release.yml , qemu in docker ,do not have BPF config , eCapture cant works with ecapture -h.

other issue : #117

Signed-off-by: CFC4N <cfc4n.cs@gmail.com>

### CODE REVIEW

**Comment by cfc4n** [comment]
@vincentmli  Cloud you test this PR ?

**Comment by vincentmli** [comment]
I just tested your PR in k8s and k3s cluster,  both not working

```
# git branch
  master
* remove-detection-bpf
  v0.1.10
  vli-dev
[root@cilium-dev ecapture]# make clean
rm -f user/bytecode/*.d
rm -f user/bytecode/*.o
rm -f assets/ebpf_probe.go
rm -f bin/ecapture
rm -f .check*

[root@cilium-dev ecapture]# make
[root@cilium-dev ecapture]# ls -l bin/ecapture 
-rwxr-xr-x 1 root root 7385088 Jul  7 14:53 bin/ecapture

# kubectl exec -it netshoot-ecap -- /bin/bash
bash-5.1# ecapture -h
2022/07/07 14:57:36 Kernel config read failed, error:KernelConfig not found.
```

**Comment by cfc4n** [comment]
Could you upload text content of `/proc/1/cgroup` when in k8s and. k3s ?

**Comment by cfc4n** [comment]
does `/.dockerenv` exist?

**Comment by vincentmli** [comment]
@cfc4n works now

```
# kubectl exec -it netshoot-ecap -- /bin/bash
bash-5.1# ecapture -h
2022/07/08 15:05:36 Your environment is a container. We will not detect the BTF config.
NAME:
	eCapture - capture text SSL content without CA cert by ebpf hook.
```

**Pull request merged**
